package com.example.vaadin1.suppliers.ui.views;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * Created by admin on 06.10.17.
 */
@DesignRoot
@AutoGenerated
public class LoginDesign extends VerticalLayout {
    public LoginDesign() {
        Design.read(this);
    }
}
